use_frameworks!

target 'SwiftyNotificationCenter_Example' do
  pod 'SwiftyNotificationCenter', :path => '../'

  target 'SwiftyNotificationCenter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
