use_frameworks!

target 'SwiftyNotificationCenter_Example' do
  pod 'SwiftyNotificationCenter', :path => '../'

  target 'SwiftyNotificationCenter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
  end
end
